<?php
session_start();
require "includes/database_connect.php";

if (!isset($_SESSION["user_id"])) {
    header("location: index.php");
    die();
}
$user_id = $_SESSION['user_id'];

$sql_1 = "SELECT * FROM users WHERE id = $user_id";
$result_1 = mysqli_query($conn, $sql_1);
if (!$result_1) {
    echo "Something went wrong!123";
    return;
}
$user = mysqli_fetch_assoc($result_1);
if (!$user) {
    echo "Something went wrong!456";
    return;
}
$sql_2 = "SELECT b.full_name,b.email,b.phone,p.name,p.address,p.rent FROM booking b INNER JOIN properties p ON b.property_id = p.id WHERE b.user_id = $user_id;";
$result_2 = mysqli_query($conn, $sql_2);
if (!$result_2) {
    echo "Something went wrong!123";
    return;
}
$row_count = mysqli_num_rows($result_2);
if ($row_count != 0) {
    $booking = mysqli_fetch_all($result_2, MYSQLI_ASSOC);
    if (!$booking) {
        echo "Something went wrong!@booking";
        return;
    }
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PG Life</title>

    <?php
    include "includes/head_links.php";
    ?>
    <link href="css/dashboard.css" rel="stylesheet" />
    <link href="css/extra.css" rel="stylesheet" />
    <style>
        .bottom {
            width: 100%;
            bottom: 0px;
        }

        .text-bold {
            font-weight: bold;
        }

        /* From uiverse.io by @hannahyockel */
        button {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            padding: 1em;
            border: 0px solid transparent;
            background-color: rgba(100, 77, 237, 0.08);
            border-radius: 1.25em;
            transition: all 0.2s linear;
        }

        button:hover {
            box-shadow: 3.4px 2.5px 4.9px rgba(0, 0, 0, 0.025),
                8.6px 6.3px 12.4px rgba(0, 0, 0, 0.035),
                17.5px 12.8px 25.3px rgba(0, 0, 0, 0.045),
                36.1px 26.3px 52.2px rgba(0, 0, 0, 0.055),
                99px 72px 143px rgba(0, 0, 0, 0.08);
        }

        .tooltip {
            position: relative;
            display: inline-block;
        }

        .tooltip .tooltiptext {
            visibility: hidden;
            width: 4em;
            background-color: rgba(0, 0, 0, 0.253);
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            top: 25%;
            left: 110%;
        }

        .tooltip .tooltiptext::after {
            content: "";
            position: absolute;
            top: 50%;
            right: 100%;
            margin-top: -5px;
            border-width: 5px;
            border-style: solid;
            border-color: transparent rgba(0, 0, 0, 0.253) transparent transparent;
        }

        .tooltip:hover .tooltiptext {
            visibility: visible;
        }
    </style>
</head>

<body style="color: black;">
    <?php
    include "includes/header.php";
    ?>

    <nav aria-label="breadcrumb" style="padding-bottom: 40px;">
        <ol class="breadcrumb py-2">
            <li class="breadcrumb-item">
                <a href="index.php">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                Dashboard
            </li>
        </ol>
    </nav>

    <div class="my-profile page-container a" style="padding: 50px; color: white">
        <h1>My Profile</h1>
        <div class="row">
            <div class="col-md-3 profile-img-container">
                <i class="fas fa-user profile-img"></i>
            </div>
            <div class="col-md-9">
                <div class="row no-gutters justify-content-between align-items-end text-bold">
                    <div class="profile">
                        <div class="name"><?= $user['full_name'] ?></div>
                        <div class="email"><?= $user['email'] ?></div>
                        <div class="phone"><?= $user['phone'] ?></div>
                    </div>
                    <div class="edit">
                        <div class="edit-profile" data-toggle="modal" data-target="#filter-modal">Edit Profile</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />

    <div class="my-profile page-container a" style="padding: 50px; color: white">
        <h1>Token Raised</h1>
        <?php
        if ($row_count != 0) {
            foreach ($booking as $token) {
        ?>
                <div class="row">
                    <div class="col-md-10">
                        <div class="row no-gutters justify-content-between align-items-end text-bold">
                            <div class="profile col-md-auto">
                                <h3>Generated By:</h3>
                                <div class="name"><?= $token['full_name'] ?></div>
                                <div class="email"><?= $token['email'] ?></div>
                                <div class="phone"><?= $token['phone'] ?></div>
                            </div>
                            <div class="profile col-mad-auto">
                                <h3>Generated for:</h3>
                                <div class="name"><?= $token['name'] ?></div>
                                <div class="email"><?= $token['address'] ?></div>
                                <div class="phone"><?= $token['rent'] ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <form action="api/delete.php" method="POST">
                            <button type="submit" name="deleteToken">
                                <input type="hidden" name="phone" value="<?= $token['phone'] ?>" />
                                <i class="fa fa-trash" style="color: #fff;"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <br />
                <br />
            <?php
            }
        } else {
            ?>
            <div class="row">
                <div class="col-md-9">
                    <div class="row no-gutters justify-content-between align-items-end text-bold">
                        No Token Raised !
                    </div>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
    <br />
    <div>
        <?php
        include "includes/footer.php";
        ?>
    </div>
    <div class="modal fade" id="filter-modal" tabindex="-1" role="dialog" aria-labelledby="filter-heading" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="filter-heading">Edit Profile</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="api/delete.php" method="GET">
                        <div class="row justify-content-between" style="padding: 10px;">
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-user"></i>
                                    </span>
                                </div>
                                <input type="hidden" name="id" value="<?= $user_id ?>" />
                                <input type="text" class="form-control" name="full_name" placeholder="Full Name" maxlength="30" required>
                            </div>

                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-phone-alt"></i>
                                    </span>
                                </div>
                                <input type="text" class="form-control" name="phone" placeholder="Phone Number" maxlength="10" minlength="10" required>
                            </div>

                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-envelope"></i>
                                    </span>
                                </div>
                                <input type="email" class="form-control" name="email" placeholder="Email" required>
                            </div>

                            <div class="form-group" style="margin-left: auto; margin-right: auto;">
                                <span>I'm a</span>
                                <input type="radio" class="ml-3" id="gender-male" name="gender" value="male" />
                                <label for="gender-male">
                                    Male
                                </label>
                                <input type="radio" class="ml-3" id="gender-female" name="gender" value="female" />
                                <label for="gender-female">
                                    Female
                                </label>
                            </div>
                        </div>
                        <div class="modal-footer" style="padding: 0px;">
                            <p>
                                <button class="cta" type="submit" name="editProfile">
                                    <span class="hover-underline-animation"> Continue </span>
                                    <svg id="arrow-horizontal" xmlns="http://www.w3.org/2000/svg" width="30" height="10" viewBox="0 0 46 16">
                                        <path id="Path_10" data-name="Path 10" d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z" transform="translate(30)"></path>
                                    </svg>
                                </button>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="js/dashboard.js"></script>
</body>

</html>